server {
    listen 80;

    location /api/user-service/ {
        proxy_pass http://user-service:8000/;
    }

    location /api/tweet-service/ {
        proxy_pass http://tweet-service:8000/;
    }

    location /api/timeline-service/ {
        proxy_pass http://timeline-service:8000/;
    }
}
